import './globals.css'
import type { Metadata } from 'next'
import Header from './Header'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <title>Ngodingbentar</title>
      </head>
      <body>
        <Header />
        {children}</body>
    </html>
  )
}
